### ISSUE TITLE
CSS,JS missing on localhost created by "php artisan serve"

### ISSUE THREAD

**Issue by anantjain6** [ncs-jss/Code-Pad#20]
![screencapture-localhost-8000-2018-06-23-20_50_41](https://user-images.githubusercontent.com/22341750/41811133-576185b6-7727-11e8-8a7f-7b21b9cbad13.png)

**Comment by ankitjain28may** [comment]
It is accessed from root dir.. no need of php artisan serve and php artisan serve looks in public directory so css is missing.
